# Generated by Django 3.0.5 on 2020-04-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
