# Generated by Django 3.0.5 on 2020-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dateofrelease',
            field=models.DateField(),
        ),
    ]
